### PR TITLE
Clickable step indicators + HTML code rework

### PR DESCRIPTION
**Pull request by earshinov**
PR #143 rebased onto `develop` branch.

### CODE REVIEW

**Comment by madoar** [comment]
@earshinov the layout changes to the vertical layout lead to some visual errors:
- the step titles are not vertically centered
- the circle of the step indicators are distorted on the y-axis (vertically)

An example:
grafik

**Comment by earshinov** [comment]
@madoar , Ouch! I will try to get to it next week.

**Comment by madoar** [comment]
Thanks :)
After, this has been fixed I'm planning to publish a new release (i.e. version `4.0.0`) to npm.

**Comment by earshinov** [comment]
@madoar , I created new https://github.com/madoar/angular-archwizard/pull/159. Please have a look.

**Pull request merged**
