### PR TITLE
 For completion steps, prioritize .done CSS class over .current

### PR DESCRIPTION
**Pull request by earshinov**
Normal steps are unaffected

See https://github.com/madoar/angular-archwizard/pull/221#issuecomment-505562661

This MR is on top of https://github.com/madoar/angular-archwizard/pull/221

<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/223"></a>

### CODE REVIEW

**Comment by madoar** [comment]
I'm not sure this is the best approach. I mean we have basically two `completed` css classes which both show a step as completed, but with slightly different meanings:
- `done`: a wizard step has been completed. According to my knowledge this state can normally only be achieved by normal (non-completion step) wizard steps. The only exception are completion steps that can be exited
- `completed`: the whole wizard has been completed. This state was initially only achievable by entering a completion step. Because a normal step was set to non-complete when entering.

Does it make sense to go back to this model?

**Comment by earshinov** [comment]
Hello @madoar!

Sorry that I disappeared again... Do I understand correctly that you suggest to apply the `completed` class to completion steps only? I think it should solve the problem. Also:
- it is straightforward to implement (especially in contrast to the changes I proposed)
- it makes some sense

**Comment by madoar** [comment]
> Sorry that I disappeared again...

No problem. Nice to see you back!

>  Do I understand correctly that you suggest to apply the completed class to completion steps only?

No, but as long as it achieves the effect we want to achieve (i.e. show the whole wizard as completed when a completion step has been entered), I'm fine with it :)

The initial idea (I think in version `2.0.0`) was for the css class `done` to be used to mark a single step as processed/completed by the user. This "state" can normally be achieved by actively leaving a step via a "Next" button. The css class `completed` in turn was used to signal that the whole wizard has been completed, i.e. all significant information has been entered and the wizard should now remain in a frozen state. An example for this is after you've finished purchasing an article in an online shop. After "submitting" your order the wizard should remain frozen to allow you to see what you have ordered, where it should be delivered, etc. The frozen wizard should **not** allow you to modify your order afterwards (in a strict sense to go back to the previous steps), because you have already established a contract with the seller.

The "frozen" condition of the `completed` state has been softened by me with the `awEnableBackLinks` directive. I think this is also part of the reason for the misunderstanding we're facing about the behavior of the wizard after entering a completion-step.

**Comment by madoar** [comment]
To summarize:

If the behavior of the wizard feels the same to the user as before (i.e. the wizard visually looks and feels the same as in the last release) I'm fine with the changes! 

If you're not sure or if you have a different understanding of how a wizard should behave please tell me so that we can find a satisfactory solution to all of us. It could also be possible that my understanding of the expected behavior is wrong. The only way to be sure is by discussion!

**Comment by earshinov** [comment]
Thanks for the explanation!

I played with my version a bit, and it seems to act as 4.0.0. I clicked through a number of pages in angular-archwizard-demo. But please double-check because I could miss something...

One problem that I see with my current solution is that it can break user stylesheets targeting the `.completed` CSS class. The styles will now longer work for non-completion steps, because the class is no longer applied there.

**Comment by madoar** [comment]
This looks good! It seems like you have a merge conflict? After the conflict has been fixed I will give the PR another quick look and merge it afterwards!

**Comment by earshinov** [comment]
I have resolved the merge conflicts.

**Pull request merged**
