### PR TITLE
Update to Angular 6

### PR DESCRIPTION
**Pull request by madoar**
This PR updates the project to use Angular 6.
In addition, this PR changes the project setup to use angular-cli for running the tests, building, etc.

### CODE REVIEW

**Comment by earshinov** [comment]
Will the new version of angular-archwizard stay compatible with Angular 2+?

**Comment by madoar** [comment]
I don't think that angular-archwizard is compatible with Angular 2.
I'm not sure about Angular 4.

The reason are not the changes in this PR.
As far as I know, `angular-archwizard` version `2.1.0` is compatible with Angular 4, while version `3.0.0` is compatible with Angular 5 + 6.
`angular-archwizard` version `4.0.0` should also be compatible to Angular 5 + 6.

**Comment by earshinov** [comment]
OK, as a package user I am only concerned about Angular 5+.

But it would be convenient if compatibility was documented in the README and also via `peerDependencies` in `project.json`, which for `angular-archwizard 3.0.0`, I believe, could look like this:

```
peerDependencies: {
  "@angular/common": "~5.0,~6.0"
}
```

This way npm / yarn will warn people trying to use `angular-archwizard` with an incompatible version of Angular.

I can file a separate issue for this, if it is needed and does not yet exist.

**Comment by madoar** [comment]
Such an issue (consisting of both the necessary code/project modifications and the documentation changes), would be appreciated :)

**Comment by earshinov** [comment]
@madoar , I have now sent a little PR https://github.com/madoar/angular-archwizard/pull/152

**Pull request merged**
