### PR TITLE
Add support for Angular Ivy

### PR DESCRIPTION
**Pull request by earshinov**
<a href="https://gitpod.io/#https://github.com/madoar/angular-archwizard/pull/237"></a>

### CODE REVIEW

**Comment by earshinov** [comment]
This PR solves all problems which library users might have when trying to use angular-archwizard in an application built with Angular Ivy (the next generation angular compiler which should become the default in Angular 9).

The only problem angular-archwizard has is using abstract classes with `@Input` directives. Hopefully it will be fixed in the future, but as of now it does not work in Ivy. As [suggested](https://github.com/angular/angular/issues/30080#issuecomment-536287895) in the respective issue (https://github.com/angular/angular/issues/30080), this PR fixes the issue by adding dummy `Directive` decorators.

These dummy decorators need to have a selector (otherwise Angular 8 rejects them as invalid) and be mentioned in `NgModule`'s `declarations`. but it seems OK to omit them from `NgModule`'s `exports` (which is good because we do not want them to be visible to library users).

**Comment by earshinov** [comment]
I am not sure what is better: merge this PR or wait for Angular team to fix the Ivy issue. However, I consider it useful anyway to have this PR around for people which might soon start asking for Ivy support.

**Comment by madoar** [comment]
@earshinov thanks for taking a look at Ivy and getting it working with `angular-archwizard`!

> I am not sure what is better: merge this PR or wait for Angular team to fix the Ivy issue. However, I consider it useful anyway to have this PR around for people who might soon start asking for Ivy support.

This is a good question. I tend to lean to option two, where we don't merge this PR (at least for now) and wait until the issue in Ivy is fixed. The reason being that I think the changes require exposing internal classes (i.e. `WizardStep` and `WizardCompletionStep`) which are not intended for exposure. 

I will let this PR remain open until we know how to continue so that interested people can apply it to their own build in case they want to use Ivy.

**Comment by earshinov** [comment]
Agree

**Comment by madoar** [comment]
@earshinov the linked issue has been closed! I believe we have good chances that Ivy will work now with a less invasive approach. Could you by change give it a try?

**Comment by earshinov** [comment]
Yep, angular-archwizard works fine with Angular 9.0.0-rc3 without this fix. Let's close this PR.

**Pull request closed without merging**
