### PR TITLE
Add support for IE < 11 

### PR DESCRIPTION
**Pull request by AbdelrhmanSafwat789**
Those commits fix issue #94 
change hidden property to class.hidden
add class hidden to wizard step component css file

### CODE REVIEW

**Comment by madoar** [comment]
First, thank you for your PR!

I haven't found the time to test this yet, but when looking at the code I have the following questions:
- you've added a `.hidden` class to the wizard-step and wizard-completion-step, I don't think this will work for custom wizard steps, which use the `awWizardStep` or `awWizardCompletionStep` directive (see https://github.com/madoar/angular-archwizard-demo/tree/master/src/app/wizard-step-directives for an example), or does it?
- you're using a different formatting than me (which is fine), but some changes I don't really like, for example:
   ```typescript
   public stepEnter: EventEmitter<MovingDirection> = new EventEmitter<
      MovingDirection
   >();
   ```
   I don't think it makes sense to write `MovingDirection` in its own line.

   In addition I think the format should be uniform over the whole project, so I think the imports and the css files should have the same formatting.

   What I like is the formatting of `canEnter` and `canExit` it is a lot easier readable :)
- is it possible to write some tests, which test the new hidden behavior?

**Comment by AbdelrhmanSafwat789** [comment]
I would like to thank you for reviewing my PR, to be frank this is my very first PR on github. 
Regarding your points:
1. I will try and test it with custom made wizard steps using the directives 
2. I agree with you on the project format, I will fix it and push the fix 
3. I will add the tests I compiled on my local machine and push them 
Again thank you for your assist, we use the wizard intensively in our project and I wanted to help.

**Comment by madoar** [comment]
@AbdelrhmanSafwat789 are you still working on this PR?
I would love to merge this PR :)

**Comment by earshinov** [comment]
This PR looks strange to me.

First of all, the objective is not clear. What version of IE are you going to target? IE10? IE9? IE8 (well, probably not IE8 because it is not supported by Angular).

Second, even for IE10 getting rid of the 'hidden' attribute will not be enough. Current styles use flexboxes, and one can use flexboxes in IE10 only with `-ms-` prefix, see https://caniuse.com/#feat=flexbox. My guess is that without these adjustments layout will be broken in some ways. Unfortunately, I don't have IE10 at hand to prove it.

IE9 does not support flexboxes at all, so see the first point. If the component needs to support IE9, it will have to abandon flexboxes. Laying things out without them is definitely possible, but needs doing (_speaking about that, I consider it a job for someone who actually needs such support, not for the project maintainers_).

All in all, my opinion is that getting rid of the `hidden` attribute will not break anything, but it is a move in a direction the project might never go. Just a thought.

**Comment by madoar** [comment]
Yes, now that I think about it @earshinov is right, the objective of this PR is not clear.
In addition, this PR has been inactive for around 6 months, in which the code has changed quite a lot.

I'll close this PR for now.
If there is still a need to support some IE versions, feel free to open a new PR.

**Pull request closed without merging**
